version: '2'
services:
  web:
    build: .
    container_name: cricket-web
    ports:
     - "5000:5000"
    volumes:
      - .:/var/www/html
    ports:
      - 8070:80
    depends_on:
      - db
    links:
      - db:cricket-db
  db:
    build:
      context: ./cricket-db
    image: cricket-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3379:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cricket-phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=oshry81
    links:
      - db:cricket-db
    ports:
      - "8071:80"
